//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 29.10.2020 20:51:50
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace MarketApp.DataModel.Market
{
    public partial class BudgetItem
    {

        public BudgetItem()
        {
            this.DocAmendsDetails = new List<Detail>();
            OnCreated();
        }

        #region Properties

        public virtual decimal Id { get; set; }
        public virtual decimal? IdParent { get; set; }
        public virtual string Name { get; set; }

        #endregion

        #region Navigation Properties

        public virtual List<Detail> DocAmendsDetails { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
