//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 29.10.2020 20:51:50
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using Utilities.Settings;

namespace MarketApp.DataModel.Market
{
    public partial class Detail
    {

        public Detail()
        {
	        this.CreatedDate = DateTime.UtcNow;
	        this.DeletedDate = null;
	        this.Id = Guid.NewGuid().ToString();
            this.DocToDetails = new List<DocsToDetails>();
            OnCreated();
        }

        #region Properties

        public virtual string Id { get; set; }
        public virtual DateTime? CreatedDate { get; set; }
        public virtual DateTime? DeletedDate { get; set; }
        public virtual string InvoiceNumber { get; set; }
        public virtual decimal? PlanSum { get; set; }
        public virtual byte[] InvoiceFile { get; set; }
        public virtual string Coment { get; set; }
        public virtual DateTime? DocDate { get; set; }
        public virtual decimal IdBudget { get; set; }
		public virtual DateTime AccrualDate { get; set; }
		public virtual string AccountNumber { get; set; }

		#endregion

		#region Navigation Properties

		public virtual List<DocsToDetails> DocToDetails { get; set; }
        public virtual BudgetItem BudgetItem { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
